plugins:
  - jest
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-console: off
  import/extensions: off
